import profile_pic from "./images/profile_pic.jpeg";
import react_is from "./images/react_is.jpeg";
import sql from "./images/SQL for Beginners.jpeg";
import html from "./images/html.jpeg";
import rdd from "./images/rdd.jpeg";
import js from "./images/js.jpeg";
import java from "./images/java.jpeg";
import mvc from "./images/mvc.jpeg";
import api from "./images/api.jpeg";
import sql2 from "./images/sql.jpeg";
import dbms from "./images/dbms.jpeg";
import ai from "./images/ai.jpeg";
import pl from "./images/pl.jpeg";
import react from "./images/react.jpeg";
import redux from "./images/redux.jpeg";
import coph from "./images/coph.jpeg";
import sc from "./images/sc.jpeg";
import course from "./images/course.jpeg";
import todopink from "./images/todopink.jpeg";

export default {
  personal_info: {
    name: "Sagnik Ghosh",
    title: "Associate at Cognizant",
    headline:
      "Aspiring Full Stack Developer with 2+ years of experience, a strong passion for DSA, problem-solving, and a commitment to lifelong learning.",
    location: {
      city: "Kolkata",
      state: "West Bengal",
      country: "India",
    },
    contact_info: {
      email: "temp@gmail.com",
      phone: "+91 0909090909",
      linkedin: "https://www.linkedin.com/in/sag-lyf/",
      github: "https://github.com/Sagnik-Coder24",
      twitter: "https://x.com/sag_lyf",
      medium: "https://medium.com/@gosagnik",
      leetcode: "https://leetcode.com/u/sag_lyf/",
    },
    profile_picture: profile_pic,
  },
  summary:
    "As a Software Engineer at Cognizant, I am passionate about coding 💻 and dedicated to continuous learning 📚. Every day, I focus on refining my technical skills and growing as a software engineer. Currently, I am focused on mastering the MERN stack (MongoDB, Express, React, Node.js) and deepening my understanding of Data Structures & Algorithms (DSA) 🔍, which I consider essential for building efficient, scalable solutions ⚙️. I have solved over 100 problems on platforms like Leetcode, significantly strengthening my problem-solving abilities.\n\nWith hands-on experience in React and Frontend Development 🌐, I thrive on tackling complex challenges and contributing to innovative projects 🚀. My strong problem-solving mindset 🧠, combined with my ability to quickly adapt to new technologies 🔄, drives my commitment to staying ahead of trends in the tech industry. I am eager to collaborate with like-minded professionals to create impactful solutions that address real-world problems and deliver lasting value.\n\nOutside of work, I enjoy working out 🏋️‍♂️, photography 📸, gaming 🎮, and, of course, coding — always exploring new ways to grow both professionally and personally.",
  skills: {
    "Programming Languages": [
      "JavaScript",
      "Python",
      "C (Programming Language)",
      "PL/SQL",
      "SQL",
      "Core Java",
    ],
    "Web Development": [
      "React.js",
      "Front-End Development",
      "HTML",
      "CSS (Cascading Style Sheets)",
      "SASS",
      "Tailwind CSS",
      "Bootstrap (Framework)",
      "Vite",
      "REST APIs",
      "JSON",
    ],
    "Backend Development": [
      "Node.js",
      "Spring MVC",
      "Spring Boot",
      "Java Database Connectivity (JDBC)",
      "Hibernate",
      "Java Persistence API",
      "Apache Maven",
    ],
    "Database Management": [
      "Database Management System (DBMS)",
      "PostgreSQL",
      "Firebase",
    ],
    "Problem Solving & Algorithms": [
      "Data Structures & Algorithms (DSA)",
      "Problem Solving",
      "Generative AI",
    ],
    "Version Control & Tools": [
      "Git",
      "GitHub",
      "Postman API",
      "npm",
      "Chrome DevTools",
      "Microsoft Visual Studio Code",
      "Eclipse",
    ],
    "Testing & Development Practices": [
      "Unit Testing",
      "Mockito",
      "JUnit",
      "Test-Driven Development",
    ],
    "Software & Platforms": ["Microsoft Office", "Arduino", "Spring Boot"],
    "Soft Skills": [
      "Teamwork",
      "Time Management",
      "Analytical Skills",
      "Personal Development",
    ],
    "Additional Knowledge": [
      "Physics",
      "Mathematics",
      "Engineering",
      "Object-Oriented Programming (OOP)",
      "Data Analysis",
      "ChatGPT",
    ],
  },
  experience: [
    {
      company: "Cognizant",
      role: "Associate",
      location: "Kolkata, West Bengal, India",
      duration: "Oct 2024 - Present (3 mos)",
      employment_type: "Full-time",
      work_mode: "Hybrid",
      responsibilities: [
        "Developed and maintained a Python application to calculate lost earnings due to system misalignments, utilizing SQL for efficient data management, reducing processing time by 25% and ensuring accurate monthly fund disbursements to over 10,000 participants.",
        "Maintained and supported a Java-based application for managing participant data and investments, overseeing DBMS operations, troubleshooting issues, and managing incidents via ServiceNow, ensuring minimal downtime and client satisfaction.",
        "Implemented automation solutions to streamline workflows, reducing manual work, cutting operational time and costs, and boosting productivity by 45% for both clients and internal teams.",
        "Actively enhancing Full Stack Development skills (MERN: MongoDB, Express.js, React.js, Node.js) and problem-solving capabilities through consistent practice of Data Structures & Algorithms (DSA).",
        "Collaborated with cross-functional teams to design and implement key features, aligning with business requirements and improving system performance.",
      ],
      skills: [
        "React.js",
        "JavaScript",
        "Redux",
        "DSA",
        "Bootstrap",
        "CSS",
        "Python",
        "GitHub",
        "Firebase",
        "Problem Solving",
        "Front-End Development",
        "Microsoft Office",
        "Visual Studio Code",
        "HTML",
        "SQL",
        "Tailwind CSS",
        "REST APIs",
        "Generative AI",
        "DBMS",
        "PL/SQL",
        "Git",
      ],
    },
    {
      company: "Cognizant",
      role: "Programmer Analyst",
      location: "Kolkata, West Bengal, India",
      duration: "Aug 2023 - Sep 2024 (1 yr 2 mos)",
      employment_type: "Full-time",
      work_mode: "Hybrid",
      responsibilities: [
        "Collaborated with business and technical teams to translate business requirements into technical solutions, ensuring efficient implementation of features.",
        "Worked on SQL database optimization, improving data retrieval speeds, and ensuring data integrity across multiple databases.",
        "Contributed to codebase documentation, ensuring easier development and troubleshooting for future team members.",
        "Managed and resolved incidents through ServiceNow, improving operational efficiency and client satisfaction.",
      ],
      skills: [
        "Python",
        "SQL",
        "JavaScript",
        "Problem Solving",
        "React.js",
        "DBMS",
        "Front-End Development",
        "Microsoft Office",
        "Visual Studio Code",
        "GitHub",
        "Data Analysis",
      ],
    },
    {
      company: "Cognizant",
      role: "Programming Analyst Trainee",
      location: "Kolkata, West Bengal, India",
      duration: "Aug 2022 - Jul 2023 (1 yr)",
      employment_type: "Full-time",
      work_mode: "Hybrid",
      responsibilities: [
        "Completed an extensive training program in Full Stack Development (Java, React.js, ADM), applying skills to build full-stack applications.",
        "Contributed to client-facing applications, enhancing user experience, functionality, and ensuring scalability and performance.",
        "Focused on Java back-end development and integrated React front-end components to streamline client solutions.",
      ],
      skills: [
        "Python",
        "SQL",
        "JavaScript",
        "React.js",
        "DSA",
        "Problem Solving",
        "Front-End Development",
        "Microsoft Office",
        "GitHub",
        "Visual Studio Code",
        "Data Analysis",
        "OOP",
        "Core Java",
        "DBMS",
      ],
    },
    {
      company: "Cognizant",
      role: "Intern",
      location: "Kolkata, West Bengal, India",
      duration: "Feb 2022 - Jul 2022 (6 mos)",
      responsibilities: [
        "Interned alongside final semester at university, gaining real-world exposure to software development processes.",
        "Contributed to the design, development, and testing of software applications within the ADM-Java-React domain, building scalable solutions.",
        "Developed high-performance React.js applications, improving speed and responsiveness by managing state with React Hooks.",
        "Integrated REST APIs to enable dynamic data fetching and real-time updates, ensuring seamless frontend-backend communication.",
        "Built scalable backend services with Java and Spring Boot, ensuring performance under high traffic loads.",
        "Managed and optimized SQL databases, enhancing query performance through indexing and normalization.",
        "Leveraged Git for version control, streamlining collaboration and maintaining consistent development practices.",
      ],
      skills: [
        "React.js",
        "JavaScript",
        "SQL",
        "Core Java",
        "CSS",
        "Spring MVC",
        "GitHub",
        "Problem Solving",
        "SASS",
        "Visual Studio Code",
        "Bootstrap",
        "npm",
        "JDBC",
        "Postman API",
        "HTML",
        "DSA",
        "Spring Boot",
        "OOP",
        "REST APIs",
        "DBMS",
        "Git",
      ],
    },
  ],
  education: [
    {
      degree: "Bachelor of Technology - BTech, Applied Electronics",
      university: "Heritage Institute of Technology",
      location: "Kolkata, West Bengal, India",
      graduation_year: 2022,
      grade: "8.41",
      activities: ["Photography Club", "Coding Club", "Gaming Club"],
      coursework: [
        "Programming",
        "Digital Electronics",
        "Embedded Systems",
        "Control Systems",
        "System Design",
        "Circuit Analysis",
        "Digital Image Processing",
      ],
      additional_learning: [
        "Web Development: Front-end (HTML, CSS, JavaScript, React, Bootstrap)",
        "Back-end (Java, Spring Boot)",
      ],
    },
    {
      degree: "High School, Science",
      university: "South Point High School",
      location: "Kolkata, West Bengal, India",
      graduation_year: 2018,
      grade: "8.0",
      activities: [
        "Handball Team - Played as a key member, promoting teamwork, strategy, and physical fitness",
      ],
      coursework: ["Physics", "Chemistry", "Mathematics", "Computer Science"],
    },
  ],
  certifications: [
    {
      img: react_is,
      title: "React Training",
      organization: "Internshala Trainings",
      date: "Sep 2021",
      url: "https://trainings.internshala.com/s/v/132756/72774ffd",
    },
    {
      img: sql,
      title: "SQL for Beginners",
      organization: "Udemy",
      date: "Mar 2022",
      url: "https://ude.my/UC-8aede5dc-68eb-4e6c-a9d9-5df714ccc93a",
    },
    {
      img: html,
      title: "Responsive Web Design",
      organization: "Udemy",
      date: "Mar 2022",
      url: "https://ude.my/UC-55cd2c51-4c97-45dd-b35f-09874788aebf",
    },
    {
      img: rdd,
      title: "Relational Database Design",
      organization: "Udemy",
      date: "Mar 2022",
      url: "https://ude.my/UC-940507d9-d874-4892-93c4-d82711a387b1",
    },
    {
      img: js,
      title: "JavaScript Basics",
      organization: "Udemy",
      date: "Mar 2022",
      url: "https://ude.my/UC-532a0cde-c0e1-4174-82f9-6beedfd56e3a",
    },
    {
      img: java,
      title: "Core Java Made Easy",
      organization: "Udemy",
      date: "Apr 2022",
      url: "https://www.ude.my/UC-a6f0de4c-210d-4969-9363-3cf544c8037f",
    },
    {
      img: mvc,
      title: "Spring MVC",
      organization: "Udemy",
      date: "May 2022",
      url: "https://ude.my/UC-bc538abf-a375-42e8-81bc-a8e0d7747bbf",
    },
    {
      img: api,
      title: "REST APIs with Postman",
      organization: "Udemy",
      date: "Aug 2022",
      url: "https://ude.my/UC-faecb1b3-713c-41e6-b2e4-e3638fecd10f",
    },
    {
      img: sql2,
      title: "The Complete Oracle SQL Certification Course",
      organization: "Udemy",
      date: "Oct 2022",
      url: "https://ude.my/UC-10b45f2c-7ba5-4d80-9771-dfe1d2008c67",
    },
    {
      img: dbms,
      title: "Database Management System",
      organization: "Udemy",
      date: "Aug 2023",
      url: "https://ude.my/UC-8dc051cf-b65d-4f96-9af0-76e228167338",
    },
    {
      img: ai,
      title: "Complete ChatGPT Course",
      organization: "Udemy",
      date: "May 2024",
      url: "https://ude.my/UC-6291e84e-f411-40c8-8a65-ac82313531f6",
    },
    {
      img: pl,
      title: "Beginner to Advanced PL/ SQL",
      organization: "Udemy",
      date: "Sep 2024",
      url: "https://ude.my/UC-4636347e-955d-410d-8ac8-89f9a6f6953e",
    },
    {
      img: react,
      title: "The Ultimate Redux Course 2023",
      organization: "Udemy",
      date: "Oct 2024",
      url: "https://ude.my/UC-044bf1f4-c6e5-4b20-ac24-30d3457920b1",
    },
    {
      img: redux,
      title: "Complete React JS web developer with ES6",
      organization: "Udemy",
      date: "Oct 2024",
      url: "https://ude.my/UC-515494f3-15cb-40b7-8112-0f2170df6ce2",
    },
  ],
  projects: [
    {
      title: "Simple Calculator",
      description:
        "This project demonstrates the creation of a simple calculator using React.js, showcasing React's state management and component-based architecture. It highlights how to build dynamic and interactive UIs with clean, reusable code. Ideal for beginners or those looking to refine their React skills.",
      technologies: ["React", "JavaScript", "HTML", "CSS"],
      url: "https://sagnik-coder24.github.io/Simple-Calculator/",
      gh: "https://github.com/Sagnik-Coder24/Simple-Calculator",
      img: sc,
    },
    {
      title: "Comfy House: Your Online Furniture Haven",
      description:
        "Comfy House is a sleek furniture shopping site that showcases my HTML, CSS, and JavaScript skills. It offers a smooth, responsive shopping experience, allowing users to browse items, add them to a cart, and view selections seamlessly on both desktop and mobile devices.",
      technologies: ["HTML", "CSS", "JavaScript", "JSON"],
      url: "https://sagnik-coder24.github.io/Comfy-House/",
      gh: "https://github.com/Sagnik-Coder24/Comfy-House",
      img: coph,
    },
    {
      title: "Course Purchase",
      description:
        "The Course Purchase app is a React project that lets users browse and select courses with a user-friendly interface. Built with React and Vite, it focuses on React hooks, state management, and props drilling.",
      technologies: ["React", "Vite", "JavaScript", "CSS"],
      url: "https://sagnik-coder24.github.io/Course-Purchase/",
      gh: "https://github.com/Sagnik-Coder24/Course-Purchase",
      img: course,
    },
    {
      title: "Todos List: Stay Organized, One Task at a Time",
      description:
        "The Todos List app is a React-based task manager that lets users add, manage, and delete tasks with an intuitive interface, built using Bootstrap for a clean layout.",
      technologies: ["React", "JavaScript", "HTML", "CSS", "Bootstrap"],
      url: "https://mytodoslist2407.netlify.app/",
      gh: "https://github.com/Sagnik-Coder24/Todos-List",
      img: todopink,
    },
  ],
  languages: [
    {
      language: "English",
      proficiency: "Native",
    },
    {
      language: "Spanish",
      proficiency: "Fluent",
    },
  ],
  awards: [
    {
      title: "Employee of the Year",
      organization: "Tech Innovators Inc.",
      date: "2023-12-01",
      description:
        "Awarded for outstanding performance and leadership in delivering high-impact projects.",
    },
  ],
  volunteer_experience: [
    {
      role: "Volunteer Web Developer",
      organization: "Code for Good",
      location: "San Francisco, CA",
      start_date: "2021-05-01",
      end_date: "Present",
      description:
        "Building and maintaining websites for non-profits to support their outreach efforts.",
    },
  ],
  interests: [
    "Artificial Intelligence",
    "Open Source Software",
    "Tech Startups",
    "Traveling",
    "Photography",
  ],
  publications: [
    {
      title: "Modern Web Development",
      journal: "Tech Trends Journal",
      date: "2023-03-15",
      url: "https://www.example.com/publication",
    },
    {
      title: "Exploring Microservices Architecture",
      journal: "DevOps Insights",
      date: "2022-08-10",
      url: "https://www.example.com/publication-2",
    },
  ],
};
